### ISSUE TITLE
already initialized constant errors

### ISSUE THREAD

**Issue by WheresWardy** [cowboyd/mvcli#11]
I'm getting the following errors from the mvcli gem when using rumm:

```
/usr/local/lib/ruby/gems/1.9.1/gems/mvcli-0.0.14/lib/mvcli/router.rb:7: warning: already initialized constant RoutingError
/usr/local/lib/ruby/gems/1.9.1/gems/mvcli-0.0.14/lib/mvcli/router.rb:8: warning: already initialized constant InvalidRoute
```

**Comment by cowboyd** [comment]
Not to nitpick, but these are warnings, not errors. It seems like something is funky in your setup that it should be evaluating the same file twice.

 I'll go ahead and change it to reopen the class instead of assign it as a constant, but you may want to have a look into why that is happening in the first place as it may cause subtle problems for you.
